### ISSUE TITLE
Error in normalizePath: (Windows 7, R:3.4.1, Rstudio 1.1.350)

### ISSUE THREAD

**Issue by sco-lo-digital** [haozhu233/giphyr#2]
Hi,

I'm getting the following error after I run `giphyr:::gif_Addin()`

`Error in normalizePath: path[1]="d:/RCompile/CRANpkg/lib/3.4/miniUI/www": The system cannot find the path specified`

Any ideas? Thanks for a great package!

**Comment by haozhu233** [comment]
Hey, thanks for bringing this up! They probably changed the namespace of miniUI in recent release. 

I just fixed this bug by extending the NS importing from `miniUI` (at least it's fixed on my computer). You can try to install from github. I will submit a CRAN update later today as it's a critical bug
