### ISSUE TITLE
Can not see thumbnails of gifs

### ISSUE THREAD

**Issue by sco-lo-digital** [haozhu233/giphyr#3]
Hi

Running R version 3.4.1 (2017-06-30) -- "Single Candle", RStudio Version 1.0.153 , Win 7

The giphyr add-in works initially, but after I search the thumbnails are question marks. I get the below error. Thanks!

```
Error from Console:
Warning in charToRaw(enc2utf8(text)) :
  argument should be a character vector of length 1
all but the first element will be ignored
Warning in if (!is.na(attribValue)) { :
  the condition has length > 1 and only the first element will be used
```

**Comment by haozhu233** [comment]
Thanks for reporting and sorry for this super late reply.... Somehow I didn't see the notification in September....... 😅

Anyway, it was introduced by some updates in other packages. I have fixed them in de dev version and will release the CRAN very soon.
