### ISSUE TITLE
Couldn't normalize path in `addResourcePath`

### ISSUE THREAD

**Issue by CodingTigerTang** [haozhu233/giphyr#5]
excited about this package!!! However, I encountered the warning below after I run add_gifs(). Any insights? 

Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'miniUI-0.1.1.1'; `directoryPath` = 'd:/RCompile/CRANpkg/lib/3.4/miniUI/www'
  [No stack trace available]

**Comment by haozhu233** [comment]
@CodingTigerTang I remember I fixed a bug like this before. Can you let me know which version of this package you are using?

**Comment by haozhu233** [comment]
Or try out the latest github version~

Also, it would be nice if you can tell me the version of miniUI you are using.

**Comment by CodingTigerTang** [comment]
> packageVersion("miniUI")
[1] ‘0.1.1.1’
> packageVersion("giphyr")
[1] ‘0.1.3’

**Comment by CodingTigerTang** [comment]
github version works !

**Comment by papayarules** [comment]
I have the same error even with the github version. In addition to the same error @CodingTigerTang posted, I also get this error in the console when loading the library
Error in fetch(key) : 
  lazy-load database 'C:/Users/User/Documents/R/win-library/3.5/giphyr/help/giphyr.rdb' is corrupt

**Comment by haozhu233** [comment]
@CodingTigerTang sometimes R on windows has this kind of issues. I will try to restart your session and reinstall this package from github.

**Comment by haozhu233** [comment]
@nickeatingpizza ops @ing the wrong person

**Comment by moodymudskipper** [comment]
Updating to github version worked for me too, consider submitting to CRAN! :)
